### ISSUE TITLE
Discord Bot specs

### ISSUE THREAD

**Issue by tomzmtl** [tomzmtl/Saltistic#13]

**Comment by DrDyne** [comment]
As a player, I want to be able to interact with a bot on Discord to get...
- statistics about me as a player (!salt RY)
- statistics about a specific game character (!salt Mario)
- statistics about me in a team (!salt RY and Mr.Petate)

**Comment by DrDyne** [comment]
https://github.com/hammerandchisel/airhornbot <-- open source discord bot

**Comment by tomzmtl** [comment]
AirHornBot is written in Go.
PHP library for Discord API: https://github.com/Cleanse/discord-hypertext

Not sure about our implementation.. where should the bot code be hosted?
The main app server, a dedicated server?

**Comment by DrDyne** [comment]
As a tournament admin, I want to be able to create and follow-up a match between 2 players...
DrDyne: !matchup RY and Mr.Petate
SaltBot: How many stocks?
DrDyne: 2
SaltBot: What is RY playing?
DrDyne: ZSS
SaltBot: What is Mr.Petate playing?
DrDyne: Cloud
SaltBot: Match #482 is running, GL & HF
...
DrDyne: !matchup #482 2 1
SaltBot: GG RY !
...

DrDyne: !matchup #482
SaltBot: RY vs Mr.Petate 2 - 1
SaltBot: http://saltistics.io/matchups/482

**Comment by DrDyne** [comment]
This is only a proposition.

**Comment by DrDyne** [comment]
The bot can be hosted wherever. It should have a low-enough profile on resources to be hosted on the main app server.

**Comment by tomzmtl** [comment]
@DrDyne is `!salt` a general keyword to access all Saltistic commands?

Can it be used to prefix subcommands like
- `!salt score RY`
- `!salt wins RY`
- `!salt avg RY`
- etc

**Comment by tomzmtl** [comment]
@DrDyne Nevermind, saw your other post.

**Comment by DrDyne** [comment]
https://discordapp.com/invite/0SBTUU1wZTUzBx2q <-- discord community server to talk about discord Bots.
The more I think about that, the more I want to code it (I might also code one for eve-online).

**Comment by tomzmtl** [comment]
Be my guest. One thing is certain: I need to expose the features we want to use in the app.

Something like (salt-y-meter score, for instance):

```
GET saltistic.petate.io./api/v1/salt/RY

{
  score: 24,
  rank: 3
}
```

**Comment by DrDyne** [comment]
yep

**Comment by tomzmtl** [comment]
Public API issue: https://github.com/tomzmtl/Saltistic/issues/15

**Comment by tomzmtl** [comment]
Public API release 1 is live!
See docs here: https://github.com/tomzmtl/Saltistic/wiki/Public-API-docs
