### ISSUE TITLE
Tournament feature specs

### ISSUE THREAD

**Issue by tomzmtl** [tomzmtl/Saltistic#14]
Specs for tournament generator.

**Comment by tomzmtl** [comment]
@CaptainPafff

**Comment by DrDyne** [comment]
My proposition:

Make a static list of stages available for tournaments (+ custom stages (can be free form or Custom A, Custom B, Custom C))

Make counter-pick rules.

Tournament type: 1v1 (2 stocks, Best of 3), 1v1 (3 stocks, 1 match), 2v2, etc...

Finals type: X stocks, best of Y (I've played double brackets elimination and finals were best of 5, gotta get the hype going)

**Comment by tomzmtl** [comment]
I would also suggest breaking down the tourney module into smaller milestones to make development quicker and focused.

Example:

#### Release 1
- Brackets only (2 stocks, best of 3).
- Select available players from registered players.
- Add game results to DB.

#### Release 2
- Ability to add guests (only matchups between registered players will be synced with DB).
- Group phase with distinct rules (2 stocks, 1 game).

#### Release 3
- More rules for finals games (best of 5)
- More rules for group phase games (3 stocks/2 games)
- Pick/counter pick system for stages.

This is only a suggestion, IMO it could be even more broken down.

**Comment by TheCaptainPaf** [comment]
Good Idea guys,

What I think to do for the Tournament feature is a generic system. I mean let the possibility to do anything you want :
- team size : 1 to 4
- number of stocks : 1 to 4 (If I remember well 4 is the max ?)
- number of match : 1 to 5 (5 is the max ?)
- Time Limit : I don't know min and max on the game
- Tournament type : Championship / Brackets

Can also add :
- stage : random, list or specific
- stage type : Normal, Omega, ...
- Character type : selected (for the whole tournament), changeable, random (I think it could be fun to do a "All-random" tournament :p)

And the tournament creator select which values he wants for each options.

**Comment by tomzmtl** [comment]
Here are the suggested requirements we want to meet for release 1:
- Team size: 1
- Stocks: 2
- Games: best of 3
- Type: brackets

The following attributes are irrelevant to the app because not used anywhere:
- Time limit
- Character type (app only stores character actually played)
- Stage

Stage randomizer may eventually be integrated in the system.
